3 + 5
7 - 4
3 * 2
print(6 / 3) # will ALWAYS return a float
print(2 ** 2) #exponent, or raise a number to a power

# There is priority of there are multple equations on a line
# PEMDAS(LR) applies in Python
# () Parentheses 1
# ** Exponents 2
# *  Multiplication 3
# /  Division 3
# +  Addition 4
# -  Subtraction 4

# Which ever equation is most to the left, takes priority

print(3 * 3 + 3 / 3 - 3)
print(3 + 3 / 3 * 3 - 3)